# Generated by Django 4.2.7 on 2024-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("speciality", models.CharField(max_length=100)),
                ("sub_speciality", models.CharField(max_length=100)),
                ("qualification", models.TextField()),
                ("experience", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("availability", models.CharField(max_length=100)),
                ("additional_details", models.TextField()),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
