# Generated by Django 4.2.7 on 2024-03-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FormApp", "0003_alter_doctor_additional_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience",
            field=models.IntegerField(max_length=500),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="qualification",
            field=models.CharField(max_length=500),
        ),
    ]
